jupyter:
  image: ghcr.io/pzktit/cryptonotebooks
  container_name: cryptonotebooks
  restart: "on-failure"
  ports:
    - 8888:8888
  volumes:
    - "./notebooks:/home/jovyan/work"
  environment:
    JUPYTER_ENABLE_LAB: "yes"
    JUPYTER_TOKEN: "password"
